### ISSUE TITLE
circle frame on flutter web problems on mobile chrome

### ISSUE THREAD

**Issue by kiaxseventh** [chooyan-eng/crop_your_image#33] opened 2021-04-09 10:44 UTC
dear @chooyan-eng 

circle frame on flutter web mobile chrome has problem

i tried it with this command :
`flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0
`
you can see result in this video :

https://user-images.githubusercontent.com/15640035/114166720-59992780-9943-11eb-9663-02204cb626b9.mp4

circle shape frame doesn't work

**Comment by kiaxseventh** [comment] 2021-04-09 10:56
i traid again with web-renderer canvaskit with this command :
`flutter run -d web-server --web-renderer canvaskit --web-port 8080 --web-hostname 0.0.0.0
`
you can see result in this video :

https://user-images.githubusercontent.com/15640035/114167281-fd82d300-9943-11eb-8128-8689494fcfd8.mp4

with canvaskit _circle shape frame is good_ but The _image aspect ratio_ is not displayed correctly

**Comment by kiaxseventh** [comment] 2021-04-09 10:57
my example image take with default camera of Samsung A70 : 
https://user-images.githubusercontent.com/15640035/114167674-7f72fc00-9944-11eb-89bb-8e51a6edf688.jpg


I tested this test with these devices with their own camera :
A70
A20
S7 
S9 
A31

i tried this test with these flutter versions :

Flutter 2.0.2 • channel stable
Flutter 2.0.3 • channel stable
Flutter 2.0.4 • channel stable


crop_your_image 0.5.3


You know the example code I used in the above videos  :smile:
https://github.com/chooyan-eng/crop_your_image/issues/31#issuecomment-810772464

**Comment by chooyan-eng** [comment] 2021-04-09 13:13
@kiaxseventh 
Thank you for reporting this issue.
I'm afraid that it may take longer than solving other bug-fixes as I'm not familiar with Flutter web and need trials & errors.

I'll start to reproduce this issue at first anyways. Thanks.

**Comment by nwparker** [comment] 2021-05-01 23:48
I can also confirm this issue.

The following title would be more accurate for this issue:
**Crop frame does not show when using Flutter Web's HTML renderer**

Do you mind updating this @kiaxseventh

@chooyan-eng , the issue can be easiest reproduced by simply adding the option `--web-renderer html` when launched flutter web (`flutter run -d chrome` => `flutter run -d chrome --web-renderer html`) .

Please let me know if you need any help setting up a working web example and I'd be happy to assist. And thank you for your work on the library thus far.

**Comment by nwparker** [comment] 2021-05-02 07:59
I'm fairly confident this is a bug with Flutter's HTML renderer

I've opened the relevant issues here:
https://github.com/flutter/flutter/issues/81637

**Comment by jkydevelopment** [comment] 2023-02-20 17:29
I faced the same issue with Flutter 3.7.0 on release version on mobile chrome. 
I'm using version `crop_your_image: ^0.7.4`.
How could I fix this?

**Comment by PcolBP** [comment] 2023-07-11 21:37
Issue was fixed 6mo ago on flutter engine. Try test it maybe on flutter master. It is flutter engine issue. 

We have to wait for newest stable release

**Comment by chooyan-eng** [comment] 2024-02-09 14:40
As long as I checked with the latest version `1.0.0-dev.2`, the problem is fixed.

<img src="https://github.com/chooyan-eng/crop_your_image/assets/20849526/fdc54c13-c8c9-4d0e-9f3e-041b5c57a77a" width=300>

I'll close this issue.

**Closed by chooyan-eng** 2024-02-09 14:40 UTC
